name: Post-release

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build UI
        working-directory: ./ui
        run: npm run build

      - name: Publish UI package
        working-directory: ./ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Tag release and push tag
        run: |
          TAG="v$(node -p \"require('./package.json').version\")"
          git tag $TAG
          git push origin $TAG
